$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    responsive:{
        0:{
            items:1
        },
        750:{
            items:2
        },
        1100:{
            items:3
        }
    }
})